[package]
name = "host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
witx-bindgen-rust = { git = "https://github.com/wasmerio/witx-bindgen", features = ["old-witx-compat"] }
